### ISSUE TITLE
AA 4.0: Class generation does not compile with generated class as custom annotation value

### ISSUE THREAD

**Issue by couchcrew-thomas** [excilys/androidannotations#1707]
This issue currently breaks my transition from AA 3.3.2 to 4.0:
When I am using the class of a generated activity as value for an annotation, the compiler fails with the error: `Error:(25, 17) error: incompatible types: String cannot be converted to Class`

To reproduce implement this simple test case:

    /**
     * Annotation to test AA class creation
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    public @interface TestAnnotation {
    
        Class value();
    }

    /**
     * Annotated activity for value to test annotation bug
     */
    @EActivity
    public class TestAnnotationValueClass extends Activity {
    
    }

    /**
     * Annotated activity to test annotation bug
     */
    @EActivity
    @TestAnnotation(TestAnnotationValueClass_.class)
    public class AnotherActivity extends Activity {
    
    }

Is there a reason this does not work anymore? It worked in 3.3.2.

**Comment by WonderCsabo** [comment]
Are you sure it worked in 3.3.2? AFAIK this never worked, the problem is that you are passing a generated class as the annotation value, but that class is not know in the annotation processing round, so we just add "<error>" instead of the class...

**Comment by couchcrew-thomas** [comment]
Yes i am very sure. It is part of our architecture to preload data for activities:

The AA annotated service loading the data is parsed from the annotation of your AA annotated activities and created via reflection.

**Comment by WonderCsabo** [comment]
Can you create a test project where we can easily switch between AA versions?

**Comment by couchcrew-thomas** [comment]
I just found out that its a matter of submodules:

Currently the generated classes used as values are classes generated inside a library module.
When using them as annotation values in the annotated class of another module the compilation succeeds. But it fails if they are referenced inside the same module which makes sense based on your explanation. Since we never referenced inside the same module before it can as well fail in 3.3.2.

Couldn't this be done in a post processing step? Like checking again for not found references after generation?

**Comment by WonderCsabo** [comment]
@couchcrew-thomas yeah, it could be done in the next processing round, but it would be really hard to implement in our current architecture.

@dodgex i am really not sure about this whole annotation copying thing. It does help in a few cases, but adds lots of problems in others.

**Comment by couchcrew-thomas** [comment]
Sorry i pushed the wrong button.

We currently use annotations for a lot of things using reflection. Like attaching test loggers etc. Removing copying of annotations would be a dealbreaker in our case.

**Comment by WonderCsabo** [comment]
But do you need those annotation on the generated classes as well?

**Comment by couchcrew-thomas** [comment]
In my specific case we should be fine by making our annotations inheritable by adding `@Inherited` but there are a lot frameworks out there using annotations where one could not change the annotation's annotations. For example libraries like Jackson, ORMLite (and a lot of other ORM libraries).
And if an annotation is not annotated with `@Inherited` using `this.getClass.getAnnotation(...)` of a generated activity would return null.
I see that my case with the generated class types as annotation values is somewhat special and not supporting it is understandable, but removing annotation copying alltogether would not be a good decision IMO.

**Comment by WonderCsabo** [comment]
Yeah, when we copy annotations which does not have generated values in them, we are fine.

I would close this issue then, because this will be not supported in the foreseeable future.

**Comment by couchcrew-thomas** [comment]
Yeah close it. I'll understand that its too special. I was thinking it worked before but was not aware of the modules being the reason.

**Comment by WonderCsabo** [comment]
No problem! I hope you can solve this at your side.
