### ISSUE TITLE
@Extra  intent for List<Serializable>  meet error when build in 4.1.0  but no problem in 3.2

### ISSUE THREAD

**Issue by yandeqing** [excilys/androidannotations#1857]
@Extra  intent for List<Serializable>  meet error when build in 4.1.0  but no problem in 3.2

**Comment by dodgex** [comment]
when you post the error and maybe some code of usage it would greatly help us to support you with your issue....

**Comment by yandeqing** [comment]
source: 
@Extra
List<BaiyouInfo> contacts;
ps:  BaiyouInfo implements Serializable

logs below:
Error:(54, 5) 错误: Unrecognized type. Please let your attribute be primitive or implement Serializable or Parcelable or an annotated Parceler bean.
Error:(55, 22) 警告: Element contacts invalidated by ExtraHandler

**Comment by yandeqing** [comment]
ok
Problem desciption:
When I update my project to androidannotations 4.1.0 from 3.2 ,then rebuild it , the problem happens.
Realated source code : 
@Extra
List<BaiyouInfo> contacts;
// ps: BaiyouInfo implements Serializable
Error logs:
Error:(54, 5) 错误: Unrecognized type. Please let your attribute be primitive or implement Serializable or Parcelable or an annotated Parceler bean.
Error:(55, 22) 警告: Element contacts invalidated by ExtraHandler
Thinks a lot for your reply.
2016-09-26 

546218945 



发件人：Kay-Uwe Janssen <notifications@github.com>
发送时间：2016-09-26 15:35
主题：Re: [excilys/androidannotations] @Extra intent for List<Serializable> meet error when build in 4.1.0 but no problem in 3.2 (#1857)
收件人："excilys/androidannotations"<androidannotations@noreply.github.com>
抄送："yandeqing"<yan546218945@qq.com>,"Author"<author@noreply.github.com>

when you post the error and maybe some code of usage it would greatly help us to support you with your issue....

**Comment by WonderCsabo** [comment]
The problem here is that the `List<BaiyouInfo>` type does not meet the requiments to be sent to a `Bundle` as is, because it does not implement `Parcelable` or `Serializable`. However simply changing to `ArrayList` solves the problem.

**Comment by yandeqing** [comment]
ok ,thanks
