### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.androidannotations.helper.ModelConstants

### ISSUE THREAD

**Issue by Bananeweizen** [excilys/androidannotations#1742]
I've upgraded to 4.0.0. The project has a gradle build and an Eclipse configuration side by side. Both work fine with 3.3.2. Gradle also works with 4.0.0. The Eclipse annotation processor does not work with 4.0.0:
```
java.lang.NoClassDefFoundError: Could not initialize class org.androidannotations.helper.ModelConstants
	at org.androidannotations.internal.Options.<init>(Options.java:43)
	at org.androidannotations.internal.InternalAndroidAnnotationsEnvironment.<init>(InternalAndroidAnnotationsEnvironment.java:57)
	at org.androidannotations.internal.AndroidAnnotationProcessor.init(AndroidAnnotationProcessor.java:75)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.discoverNextProcessor(IdeAnnotationProcessorManager.java:93)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
There are no other errors in the error log or problems view. Everything has been cleaned and restarted after changing the annotation processor. I've repeated the process on 2 machines. The API bundle is on the library build path, while the APT bundle is in a separate folder which is only used by the Eclipse APT factory. I haven't installed any of the additional modules which exist since 4.0.0.

Any further advice on what I might need to check?

**Comment by WonderCsabo** [comment]
The problem is that we no longer produce the bundle. We only support using build tools with proper dependency resolution.

However you can still use AA with Eclipse, just check out all the dependencies and add them on the processor classpath. I think you only need AA jar, AA API jar and codemodel jar.

**Comment by Bananeweizen** [comment]
Thanks. Will follow the dependency chain.
